# Generated by Django 4.0.4 on 2022-04-25 01:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='title')),
                ('director', models.CharField(max_length=128, verbose_name='director')),
                ('rating', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)], verbose_name='rating')),
                ('description', models.TextField(verbose_name='description')),
                ('is_private', models.BooleanField(default=False, verbose_name='private item')),
            ],
        ),
    ]
